# Generated by Django 4.2.6 on 2023-11-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('price', models.FloatField()),
                ('manufacturer', models.CharField(max_length=40)),
                ('guarantee', models.IntegerField()),
                ('info', models.JSONField()),
            ],
        ),
    ]
