# Generated by Django 4.2.6 on 2023-12-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartitemmodel_cartmodel_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadressmodel',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_id', models.JSONField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('final_sum', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingadressmodel')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ordermodel'),
        ),
    ]
