# Generated by Django 4.2.6 on 2023-12-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_shippingadressmodel_address_ordermodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='products_id',
            new_name='products_ids',
        ),
    ]
