# Generated by Django 4.2.6 on 2023-12-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_products_id_ordermodel_products_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='products',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItemModel',
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
