# Generated by Django 4.2.6 on 2023-12-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='products',
            field=models.ManyToManyField(to='store.productmodel'),
        ),
    ]
