# Generated by Django 4.2.6 on 2024-02-05 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_productmodel_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='favourite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
