# Generated by Django 5.0.2 on 2024-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productmodel_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdressModel',
            new_name='ShippingAddressModel',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='favourite',
            new_name='favorite',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='info',
            field=models.JSONField(blank=True),
        ),
    ]
