# Generated by Django 5.0.2 on 2024-02-29 15:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_rename_shippingadressmodel_shippingaddressmodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="slug",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="productmodel",
            old_name="info",
            new_name="property",
        ),
        migrations.RenameField(
            model_name="productmodel",
            old_name="manufacturer",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="guarantee",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="name",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="bonus",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="image",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="promotion",
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="sale",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
