# Generated by Django 5.0.2 on 2024-02-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_code_productmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='code',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
