# Generated by Django 5.0.2 on 2024-03-21 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_productmodel_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="code",
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="id",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
