# Generated by Django 5.0.2 on 2024-03-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_category_slug_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='bonus',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
