# Generated by Django 5.0.2 on 2024-03-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_productmodel_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='code',
            field=models.PositiveIntegerField(blank=True, default=7798849),
        ),
    ]
