# Generated by Django 5.0.2 on 2024-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_productmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='code',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
